React admin with git submodule
pixiebrix/playground pull request #28
Opened 2021-12-14 11:02 UTC by EmmanuelObua

2021-12-14 13:43 UTC, twschiller commented
Thanks @EmmanuelObua. This has the same problem as the last one where if you visit it without the slash https://playground-5lhd1uc4k-pixiebrix.vercel.app/react-admin the page doesn't load

Could you introduce the same fix the you and @fregante added for the vue one?

2021-12-14 13:50 UTC, EmmanuelObua commented
> Thanks @EmmanuelObua. This has the same problem as the last one where if you visit it without the slash https://playground-5lhd1uc4k-pixiebrix.vercel.app/react-admin the page doesn't load
> 
> If you visit https://playground-5lhd1uc4k-pixiebrix.vercel.app and then click react-admin it won't load
> 
> Could you introduce the same fix the you and @fregante added for the vue demo?

I noticed this, it's failing to read the manifest.json file, I looked around and I am suspecting it's because of the way the manifest file is linked in the build index.html file with ./manifest.json syntax.

I wanted to try again by changing the way it's link in the href from ./manifest.json to manifest.json

2021-12-14 13:58 UTC, twschiller commented
The CSS and JS file are also not loading. 

![image](https://user-images.githubusercontent.com/1879821/146012151-87ff957d-7c19-4799-a452-e73be283dbd4.png)

I think you need to set the PUBLIC_URL during the build? See the build steps for the create-react-app example.

This is the index.html file of the react-admin demo. Notice that it refers to the PUBLIC_URL: https://github.com/marmelab/react-admin/blob/master/examples/demo/public/index.html#L10

2021-12-14 20:28 UTC, EmmanuelObua commented
Ok please, sounds good

2021-12-15 13:32 UTC, twschiller requested changes
@EmmanuelObua this is still not working for me when I visit without the "/" (which is the what is linked on the homepage)

![image](https://user-images.githubusercontent.com/1879821/146195642-bf825831-36c4-4a1b-bdbc-40b37c81bd9b.png)

2021-12-15 17:30 UTC, twschiller commented
Merging this in to see if it unblocks the other build

2021-12-15 17:30 UTC, merged

2021-12-15 18:15 UTC, fregante reviewed
It works now! https://playground-gjhxthfrs-pixiebrix.vercel.app/react-admin#/

Here's a couple of notes for the future reference

2021-12-15 18:15 UTC, fregante commented on react-admin/build.sh
> +PUBLIC_URL=/react-admin/
When declaring variables like this, they will only be available in the current file.


To make it available in the scripts, either use:

```
PUBLIC_URL=/react-admin/ make build
```

or 


```
export PUBLIC_URL=/react-admin/

make build
```

The `export` keyword makes it available for all the sub-processes (like `make` and `npm`)


---

I already made this change on `main` branch

2021-12-15 18:15 UTC, fregante commented on vercel.json
> +			"destination": "/react-admin/index.html"
This is not necessary when the user uses `#/` in its URLs. It can be removed